import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.css";
import Logo from "../public/logo.png";
import { useState, Fragment } from "react";

const Home = () => {
  const [skills, setSkills] = useState([{ title: "", votes: 0, id: 0 }]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={Logo} />
        <h1 className={styles.title}>Welcome to Next.js!</h1>
        <button
          onClick={() => {
            setSkills([
              ...skills,
              { title: "", votes: 0, id: skills[skills.length - 1].id + 1 },
            ]);
          }}
        >
          Add
        </button>

        {skills.map((el) => (
          <Fragment key={el.id}>
            <input
              key={el.id + "title"}
              value={el.title}
              onChange={(e) => {
                const oldSkills = skills.concat();
                console.log("oldskills", oldSkills);
                const index = oldSkills.findIndex(
                  (skill) => skill.id === el.id
                );
                console.log("index", index);
                oldSkills[index].title = e.target.value;
                setSkills(oldSkills);
              }}
            />
            <input
              key={el.id + "votes"}
              value={el.votes}
              onChange={(e) => {
                const oldSkills = skills.concat();
                console.log("oldskills", oldSkills);
                const index = oldSkills.findIndex(
                  (skill) => skill.id === el.id
                );
                console.log("index", index);
                oldSkills[index].votes = e.target.value;
                setSkills(oldSkills);
              }}
            />
          </Fragment>
        ))}
      </main>
    </div>
  );
};

export default Home;
